refactor getting started guides
aws/karpenter pull request #1193
Opened 2022-01-20 00:07 UTC by geoffcline

**1. Issue, if available:**
too many guides in left nav

**2. Description of changes:**
add new "getting started" nav section, with landing page

move guides under this new parent page

separate grafana out into own guide

**3. How was this change tested?**
netlify preview

**4. Does this change impact docs?**
- [x] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-20 09:55 UTC, mbevc1 submitted a review, later dismissed

2022-01-21 21:28 UTC, bwagner5 commented on website/content/en/preview/getting-started/next-steps-grafana/_index.md
> +### Create Grafana dashboards (optional)
Since this is its own guide now, we can get rid of the `(optional)`

2022-01-21 21:28 UTC, bwagner5 commented on website/content/en/preview/getting-started/next-steps-grafana/_index.md
> +#### Deploy a temporary Prometheus and Grafana stack (optional)
same here

2022-01-21 21:28 UTC, bwagner5 commented on website/content/en/preview/getting-started/getting-started-with-eksctl/_index.md
> +### Create Grafana dashboards (optional)
Should these two grafana sections just link to the dedicated grafana getting start guide now?

2022-02-02 17:54 UTC, geoffcline commented
revise

2022-02-02 18:13 UTC, mbevc1 approved these changes

2022-02-05 17:00 UTC, bwagner5 requested changes
I'm good to merge after the link is updated for the AWS getting started guide

2022-02-09 20:27 UTC, bwagner5 commented
After rebase, we should be good!

2022-02-25 22:52 UTC, bwagner5 approved these changes
lgtm

2022-02-25 22:52 UTC, merged