s/karpenter-metrics/karpenter
aws/karpenter pull request #1511
Opened 2022-03-14 21:28 UTC by spring1843

**1. Issue, if available:**
https://github.com/aws/karpenter/issues/1502

**2. Description of changes:**
target changed since helm refactor

**3. How was this change tested?**

**4. Does this change impact docs?**
- [x] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-14 21:29 UTC, ellistarn approved these changes

2022-03-15 16:22 UTC, bwagner5 requested changes
can you update v0.7.0 docs too?

2022-03-15 18:06 UTC, ellistarn approved these changes

2022-03-15 21:37 UTC, bwagner5 approved these changes
lgtm!

2022-03-15 21:37 UTC, merged