BREAKING CHANGE: removed instance type filtering and add them at defaulting time
aws/karpenter pull request #2779
Opened 2022-11-01 18:51 UTC by ellistarn

Fixes # 

**Description**

Instance category defaults are now explicitly persisted in the Provisioner, rather than handled implicitly in memory. By default, Provisioners will limit instance category to c,m,r. If any instance type constraints are applied, it will override this default. If you have created Provisioners in the past with unconstrained instance type, family, or category, Karpenter will now more flexibly use instance types than before. If you would like to apply these constraints, they must be included in the Provisioner CRD.

This also helps to decouple instance type from provisioner, enabling upcoming work.

**How was this change tested?**

* `make test`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [X] No

**Release Note**

```release-note
Instance category defaults are now explicitly persisted in the Provisioner, rather than handled implicitly in memory. By default, Provisioners will limit instance category to c,m,r. If any instance type constraints are applied, it will override this default. If you have created Provisioners in the past with unconstrained instance type, family, or category, Karpenter will now more flexibly use instance types than before. If you would like to apply these constraints, they must be included in the Provisioner CRD.
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-01 19:19 UTC, bwagner5 commented on pkg/apis/v1alpha5/provisioner.go
> +			Key: v1alpha1.LabelInstanceCategory, Operator: v1.NodeSelectorOpIn, Values: []string{"c", "m", "r"},
This doesn't match the default we had before, do you want to put a Generation > 2 as well?

2022-11-01 23:22 UTC, bwagner5 requested changes

2022-11-01 23:22 UTC, bwagner5 commented on pkg/apis/v1alpha5/provisioner.go
> +			{Key: v1alpha1.LabelInstanceGeneration, Operator: v1.NodeSelectorOpGt, Values: []string{"1"}},
This should be 2:

```
> ec2-instance-selector --allow-list 'm2' --region us-east-1
m2.2xlarge
m2.4xlarge
m2.xlarge
```

```suggestion
			{Key: v1alpha1.LabelInstanceGeneration, Operator: v1.NodeSelectorOpGt, Values: []string{"2"}},
```

2022-11-02 15:48 UTC, bwagner5 approved these changes
LGTM

2022-11-02 15:50 UTC, bwagner5 commented
/karpenter snapshot

2022-11-02 17:07 UTC, bwagner5 approved these changes
LGTM

2022-11-02 17:30 UTC, merged

2022-11-03 16:00 UTC, ellistarn commented on website/content/en/preview/upgrade-guide/_index.md
> +* Instance category defaults are now explicitly persisted in the Provisioner, rather than handled implicitly in memory. By default, Provisioners will limit instance category to c,m,r. If any instance
c6g, etc are of category c: https://karpenter.sh/v0.18.1/aws/instance-types/#c6g-family