feat: subnetSelector-enhancement
aws/karpenter pull request #2859
Opened 2022-11-16 03:16 UTC by smcavallo

Signed-off-by: smcavallo <smcavallo@hotmail.com>

Fixes # 

**Description**
Support comma separated tag values in `subnetSelector` - (wildcard search is not flexible enough.)
Consider the use case where `Private1,Private2` subnets should be used but `Private3` excluded.
This is a simple enough change to split the string and supported by the ec2 tag filters.
It is done this same exact way for `aws-ids` searches.

**How was this change tested?**

* Unit tests

**Does this change impact docs?**
- [X ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-16 22:57 UTC, ellistarn submitted a review, later dismissed
This is slick -- I love that this is innately supported by the AWS APIs.

2022-11-17 00:18 UTC, bwagner5 commented on pkg/cloudprovider/subnets_test.go
> -	. "github.com/onsi/gomega"
```suggestion
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
```

2022-11-17 00:18 UTC, bwagner5 commented on pkg/cloudprovider/subnets_test.go
> -	. "github.com/aws/karpenter-core/pkg/test/expectations"
```suggestion
	. "github.com/aws/karpenter-core/pkg/test/expectations"
```

2022-11-17 03:23 UTC, ellistarn approved these changes

2022-11-17 18:54 UTC, ellistarn commented
Looks like this is failing tests: https://github.com/aws/karpenter/actions/runs/3489726900/jobs/5841741532

2022-11-20 19:48 UTC, smcavallo commented
There is something wrong with the tests.  I am running this test with the original code and it is failing for the same reason.
The below should 100% have worked with the original code.
```
	It("should discover subnets by tag", func() {
		provider.SubnetSelector = map[string]string{"Name": "subnet-test2"}
		ExpectApplied(ctx, env.Client, test.Provisioner(coretest.ProvisionerOptions{Provider: provider}))
		pod := ExpectProvisioned(ctx, env.Client, recorder, controller, prov, coretest.UnschedulablePod())[0]
		ExpectScheduled(ctx, env.Client, pod)
		createFleetInput := fakeEC2API.CalledWithCreateFleetInput.Pop()
		Expect(fake.SubnetsFromFleetRequest(createFleetInput)).To(ConsistOf(
			"subnet-test2",
		))
	})
```
Looking into why....and will submit a fix....

2022-11-21 00:48 UTC, smcavallo commented
@ellistarn - thank you!!!!  Should be all fixed now and the tests should all be passing.  My confusion was from how close the subnet `Name` and `id` are.  I tried to add a comment in the tests to help anyone else who is debugging.  It took a bit to figure out where the fixture info was coming from, but all set now.

2022-11-24 03:08 UTC, ellistarn approved these changes

2022-11-27 16:42 UTC, ellistarn commented
One last thing @smcavallo, can you make an integration test in github.com/aws/karpenter/test/suites/integration/subnet_test.go. 

You can verify the test by running `FOCUS="testname from It() block" make e2etests`, which will run your singular test against a local cluster. Make sure you have your kubeconfig setup to point to somewhere where this test can execute correctly.

2022-11-27 16:43 UTC, ellistarn requested changes
Great work! Needs a test, though.

2022-12-01 04:11 UTC, smcavallo commented
@ellistarn - thanks!!!  I took a shot at writing an integration test if you can please take a look.

2022-12-01 17:37 UTC, ellistarn commented on test/suites/integration/subnet_test.go
> +type SubnetInfo struct {
Consider just passing the ec2 subnets around, rather than making another struct.

2022-12-01 17:39 UTC, ellistarn approved these changes
Nice!

2022-12-01 17:40 UTC, ellistarn commented
@smcavallo, can you put the output of a successful test run in the PR description?

2022-12-12 22:00 UTC, tzneal commented
Looks like it's just a go-lint issue renaming Id to ID is all that's remaining.

2022-12-13 03:50 UTC, smcavallo commented
thanks @tzneal!!!! It has been updated.

2022-12-13 19:39 UTC, ellistarn approved these changes
Great work! thanks!

2022-12-14 12:45 UTC, smcavallo commented
I just rebased off master to fix the tests which were referencing deprecated properties

2022-12-14 15:59 UTC, ellistarn submitted a review, later dismissed

2022-12-19 22:10 UTC, ellistarn commented
Hey @smcavallo , let me know if you want me to take over this PR to get it across the finish line.

2022-12-20 01:33 UTC, smcavallo commented
@ellistarn - YES PLEASE, that would be great - thank you so much!!!!

2022-12-27 19:06 UTC, jonathan-innis commented
Closed in favor of #3080

2022-12-27 19:06 UTC, closed without merging