docs: fix broken links related to tasks directory
aws/karpenter pull request #3081
Opened 2022-12-20 18:11 UTC by armujahid

**Description**

preview and v0.20.0 docs don't have tasks directory. Probably because all required files were moved to concepts directory

**How was this change tested?**

**Does this change impact docs?**
- [X] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-20 18:30 UTC, jonathan-innis requested changes

2022-12-20 18:30 UTC, jonathan-innis commented on website/content/en/preview/concepts/overview.md
> +See [Provisioner API](../provisioner) for a description of settings and the [Provisioning](./provisioning) task for provisioner examples.
```suggestion
See [Provisioning](./provisioning) docs for a description of settings and provisioner examples.
```

2022-12-20 18:50 UTC, armujahid commented on website/content/en/preview/concepts/_index.md
> +See [Provisioner API](../provisioner) for a description of settings and the [Provisioning](./provisioning) task for provisioner examples.
Done in all 4 files

2022-12-20 19:01 UTC, ellistarn approved these changes
lol, nice fix :)

2022-12-20 19:32 UTC, jonathan-innis approved these changes
Thanks for the contribution! LGTM 🚀

2022-12-20 20:06 UTC, merged

2022-12-21 17:53 UTC, armujahid commented
1. Why do we have a redundant [overview.md](https://karpenter.sh/preview/concepts/overview/) section when everything is already covered in [_index.md](https://karpenter.sh/preview/concepts/) ?
2. Both sessions have some drift that can seen at https://editor.mergely.com/5PoCsTEC/
3. I missed testing overview and just found that links are still broken in overview (links in overview will required double dot to move one level up). Index links are working fine.

I suggest we should remove overview.md and its link since this section is already covered in index of concepts.