docs: Update README to account for other regions
aws/karpenter pull request #3104
Opened 2022-12-23 00:58 UTC by dennisotugo

Hello, I updated the README default region to somewhere other than us-east-1, which allows us to create a secondary provider pointing to the us-east-1 where the ECR registry is stored. Covering varied use-cases

Fixes # 

**Description**

**How was this change tested?**

*

**Does this change impact docs?**
- [X ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-23 10:51 UTC, FernandoMiguel reviewed
lgtm

2022-12-23 11:06 UTC, FernandoMiguel commented on website/content/en/v0.20.0/getting-started/getting-started-with-terraform/_index.md
> +  alias = "virginia"
pls fmt

2022-12-23 16:58 UTC, ellistarn commented
The getting started guide is just a getting started guide. We expect folks to modify it to meet their needs. The more complicated this guide is, the harder it is to test, and the more likely it is to break. Changing the region is something we expect users to do when customizing the guide to meet their use case.

2022-12-23 17:00 UTC, ellistarn requested changes
The getting started guide is just a getting started guide. We expect users to customize it to meet their use cases. The more branching logic we include in this guide, the harder it is to test, and the less likely it is to be correct.

2022-12-27 20:24 UTC, jonathan-innis commented
Closing since we are consolidating these docs as part of #3017

2022-12-27 20:24 UTC, closed without merging