Update _index.md
aws/karpenter pull request #3151
Opened 2023-01-04 06:28 UTC by praseedasathaye

I am still not sure if we need this line " This is useful if there is additional room in the node due to imperfect packing shape or because workloads finish over time."?

Fixes # 

**Description**

**How was this change tested?**

*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-04 18:55 UTC, ellistarn submitted a review, later dismissed
Thanks!

2023-01-04 19:30 UTC, ellistarn approved these changes

2023-01-04 19:30 UTC, ellistarn requested changes
Can you update this in en/preview/concepts as well?

2023-01-04 19:47 UTC, ellistarn approved these changes

2023-01-05 06:51 UTC, spring1843 approved these changes
LGTM

2023-01-10 21:37 UTC, merged