docs: root volume is incorrect size in bottlerocket example manifest
aws/karpenter pull request #3621
Opened 2023-03-21 03:48 UTC by dschaaff

See https://github.com/bottlerocket-os/bottlerocket/issues/2915 for why this is needed

**Description**

In bottlerocket 1.13 it is important the root volume size is not modified from the default 2gb size. See https://github.com/bottlerocket-os/bottlerocket/issues/2915

**Release Note**

```release-note
Updated example bottlerocket node template to use 2gb root volume. See https://github.com/bottlerocket-os/bottlerocket/issues/2915
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-21 11:59 UTC, FernandoMiguel commented on examples/provisioner/bottlerocket.yaml
> +        volumeSize: 2Gi
https://github.com/aws/karpenter/pull/2400

2023-04-13 14:52 UTC, bwagner5 requested changes

2023-04-13 15:30 UTC, FernandoMiguel commented on examples/provisioner/bottlerocket.yaml
> +        volumeSize: 2Gi
i think i've tried this before, but it fails @bwagner5 .
i would have to look into it again to be sure

2023-05-02 21:18 UTC, jonathan-innis commented
It looks like https://github.com/bottlerocket-os/bottlerocket/issues/2915 has been closed which fixes this. Going to close this since this should not longer be an issue with newer versions of BR.

2023-05-02 21:18 UTC, closed without merging