update doc
aws/karpenter pull request #3887
Opened 2023-05-12 19:54 UTC by prabhjotsingh18

docs:  website/content/en/preview/getting-started/getting-started-with-karpenter/

Fixes #3791

**Description**

updated getting-started-with-karpenter scripts changing hardcoded  to use variable AWS_PARTITION

**Does this change impact docs?**
- [X] Yes, PR includes docs updates
- [X] Yes, issue opened: #3791
- [ ] No

**Release Note**
"NONE". 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-12 20:26 UTC, njtran requested changes
Thanks for the PR! Looks like there are some changes we can make in the migrating-from-cas guide too. Are you able to make those changes?

- 4 in `migrating-from-cas/scripts/step03-node-policies.sh`
- 1 in `migrating-from-cas/scripts/step05-controller-iam.sh`

2023-05-12 20:26 UTC, njtran commented on website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
> +    - arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:policy/KarpenterControllerPolicy-${CLUSTER_NAME}
Looks like there are two more occurrences on line 31 and line 53, can you add those in?

2023-05-15 17:45 UTC, jonathan-innis reviewed
I think there's one more change that needs to be made to add the `${AWS_PARTITION}` variable [here](https://github.com/aws/karpenter/blob/main/website/content/en/preview/getting-started/migrating-from-cas/_index.md?plain=1#L83) but otherwise, LGTM 🚀

2023-05-17 16:55 UTC, jonathan-innis commented
@prabhjotsingh18 Just checking that you saw my comment on the need to update the `AWS_PARTITION` in one more place

2023-05-22 20:53 UTC, jonathan-innis approved these changes
LGTM 🚀

2023-05-23 00:29 UTC, njtran approved these changes

2023-05-23 00:31 UTC, merged