Moved API doc to top level, removed ref section and faqs
aws/karpenter pull request #867
Opened 2021-11-27 23:21 UTC by chrisnegus

**1. Issue, if available:**

**2. Description of changes:**
This PR:
* Remove the FAQs section of the docs.
* Moves the "Provisioner CRD" section it up a level in the left nav and renames it "Provisioner API".
* Deletes the now-empty Reference section and associated _index file.

Much of the FAQs was outdated or already covered somewhere else. I've gone through it and will add some of that content back into other parts of the docs.

**3. Does this change impact docs?**
- [X] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-27 23:32 UTC, geoffcline approved these changes

2021-11-27 23:35 UTC, geoffcline requested changes
it looks like there is one broken link due to the moved provisioner page

> 5:22:03 PM: ERROR 2021/11/27 23:22:03 [en] REF_NOT_FOUND: Ref "../../reference/provisioner-crd.md": "/opt/build/repo/website/content/en/pre-docs/cloud-providers/AWS/aws-spec-fields.md:7:23": page not found

can you fix this chris? The link should be 

> The [Provisioner CRD]({{< ref "../../provisioner-crd.md" >}}) supports defining

2021-11-28 00:41 UTC, chrisnegus commented
> it looks like there is one broken link due to the moved provisioner page
> 
> > 5:22:03 PM: ERROR 2021/11/27 23:22:03 [en] REF_NOT_FOUND: Ref "../../reference/provisioner-crd.md": "/opt/build/repo/website/content/en/pre-docs/cloud-providers/AWS/aws-spec-fields.md:7:23": page not found
> 
> can you fix this chris? The link should be
> 
> > The [Provisioner CRD]({{< ref "../../provisioner-crd.md" >}}) supports defining

Yes. I can do that.

2021-11-28 00:54 UTC, chrisnegus commented
/assign

2021-11-28 02:29 UTC, geoffcline approved these changes

2021-11-28 02:29 UTC, geoffcline commented on website/content/en/pre-docs/cloud-providers/AWS/aws-spec-fields.md
> +The [Provisioner CRD]({{< ref "../../provisioner-crd.md" >}}) supports defining
perfect!

2021-11-28 02:29 UTC, merged