v0.5.1
aws/karpenter pull request #911
Opened 2021-12-03 19:22 UTC by ellistarn

**1. Issue, if available:**

**2. Description of changes:**

**3. Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-03 19:33 UTC, njtran requested changes
Can you make the changes to the Getting Started guide as well?

2021-12-03 19:34 UTC, ellistarn commented
Hey @tuananh, I found a way to simplify the helm README to just generate `helm-docs` whenever we run `make helm`. Since chart is published alongside release versions, we only want to update the README when we release a new version of the chart. This is important to avoid version skew. 

I just wanted to check that I'm not missing anything from you change and get your blessing on these changes.

2021-12-03 19:43 UTC, ellistarn commented
> Can you make the changes to the Getting Started guide as well?

Let's cut docs in a followon -- it's a bit complicated.

2021-12-03 19:44 UTC, njtran approved these changes

2021-12-03 19:45 UTC, merged

2021-12-04 00:12 UTC, tuananh commented
@ellistarn this works for the current manual release i guess. but later on, if you want to automate the release process of helm chart, it'll get a bit complicated because we then need CI to comit back the changes of helm-docs back which i don't think is a good idea.

what i have in mind is
- check helm-docs for every pr
- make sure the chart version bump is getting check too.

then we can automate the chart release progress, without waiting for karpenter. since i figure chart release is usually a lot more frequent than karpenter itself.

2021-12-04 00:20 UTC, ellistarn commented
> @ellistarn this works for the current manual release i guess. but later on, if you want to automate the release process of helm chart, it'll get a bit complicated because we then need CI to comit back the changes of helm-docs back which i don't think is a good idea.
> 
> what i have in mind is
> 
> * check helm-docs for every pr
> * make sure the chart version bump is getting check too.
> 
> then we can automate the chart release progress, without waiting for karpenter. since i figure chart release is usually a lot more frequent than karpenter itself.

Good points. Let's cover this in working group.

2021-12-04 00:38 UTC, tuananh commented
Sure can :)